name: AMD64
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: build
    uses: ./.github/workflows/reusable-build.yml
    with:
      path: .
      tag: amd64
